### GET
### Get all blogs
GET http://localhost:3003/api/blogs/
### Get one by ID
GET http://localhost:3003/api/blogs/6a983fa0d1c8b998306e4e1f
### Get one by non exist ID
GET http://localhost:3003/api/blogs/6a983fa0d1c8b998306e4e1e
### Get one by wrong ID (id is 0x)
GET http://localhost:3003/api/blogs/6a9843238bf537fa1fac8bfq

### DEL
DELETE http://localhost:3003/api/blogs/6a9ecddf9b2415df4998906e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjZhOWU3MGU2YTVhMjUzNzJjMDFlZWRkYSIsImlhdCI6MTc4ODc5MjI2MywiZXhwIjoxNzg4Nzk1ODYzfQ.WEnvNmHPx6a0cExL_ph-bmUbcxrcFuIsdE64fz5kH-w

### POST
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjZhOWU3MGU2YTVhMjUzNzJjMDFlZWRkYSIsImlhdCI6MTc4ODc5MjI2MywiZXhwIjoxNzg4Nzk1ODYzfQ.WEnvNmHPx6a0cExL_ph-bmUbcxrcFuIsdE64fz5kH-w

{
    "title": "Go To Statement Considered Harmful",
    "author": "Edsger W. Dijkstra",
    "url": "https://homepages.cwi.nl/~storm/teaching/reader/Dijkstra68.pdf",
    "likes": 5
}
### NO TOKEN POST
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "Go To Statement Considered Harmful",
    "author": "Edsger W. Dijkstra",
    "url": "https://homepages.cwi.nl/~storm/teaching/reader/Dijkstra68.pdf",
    "likes": 5
}
### wrong scheme
# POST http://localhost:3003/api/blogs/ HTTP/1.1
# content-type: application/json

# {
#     "important": false,
#     "content": "lol"
# }
