### GET
### Get all users
GET http://localhost:3003/api/users/

### POST
### POST ROOT
POST http://localhost:3003/api/users/ HTTP/1.1
content-type: application/json

{
    "username": "root",
    "name": "Superuser",
    "password": "salainen"
}
### POST ONE USER
POST http://localhost:3003/api/users/ HTTP/1.1
content-type: application/json

{
    "username": "mluukkai",
    "name": "Matti Luukkainen",
    "password": "mluukkai"
}
### POST INVALID USER
POST http://localhost:3003/api/users/ HTTP/1.1
content-type: application/json

{
    "username": "mluukkai",
    "name": "Matti Luukkainen"
}
### POST INVALID USER
POST http://localhost:3003/api/users/ HTTP/1.1
content-type: application/json

{
    "username": "mluukkai",
    "name": "Matti Luukkainen",
    "password": "ml"
}

